scheduler/urls.py
from django.conf.urls.defaults import *
from scheduler import views
from django.views.generic import list_detail
from django.views.generic.simple import direct_to_template
from scheduler.models import MatchDay, Proposal, Sport
from scheduler.forms import PlayerRegistrationForm, PlayerProfileForm
from scheduler.feeds import LatestMatchDays, LatestNews
from django.db.models import Count

sport_context = {'extra_context': {'sport_list': Sport.objects.annotate(Count('matchday_sport'))}}
feeds = {'latest': LatestMatchDays, 'news': LatestNews}
md_info = {'queryset': MatchDay.objects.all()}
md_info.update(sport_context)
proposal_info = {'queryset': Proposal.objects.all()}

urlpatterns = patterns('',
    url(r'^$',
        list_detail.object_list,
        dict(md_info, paginate_by = 10),
        name='sch_matchday_list'),
    url(r'^matchday/(?P<object_id>\d+)/$',
        list_detail.object_detail,
        md_info,
        name='sch_matchday_detail'),
    url(r'^matchday/(?P<object_id>\d+)/rss/$',
        list_detail.object_detail,
        dict(md_info, template_name = 'feeds/matchday_rssdetail.html'),
        name='sch_rss_detail'),
    url(r'^getemailform/(?P<object_id>\d+)/$',
        list_detail.object_detail,
        dict(md_info, template_name = 'scheduler/send_email_form.html'),
        name='sch_email_ajax'),
    url(r'^proposal/(?P<object_id>\d+)/$',
        list_detail.object_detail,
        dict(proposal_info, template_name = 'scheduler/proposal_detail.html'),
        name='sch_proposal_ajax'),
)

urlpatterns += patterns('',
    url(r'^accounts/register/$',
        'registration.views.register',
        {'form_class' : PlayerRegistrationForm,
         'backend': 'scheduler.forms.PlayerRegistrationBackend'},
        name='registration_register'),
    url(r'^profiles/edit/$',
        'profiles.views.edit_profile',
        {'form_class' : PlayerProfileForm},
        name='profiles_edit_profile'),
    url(r'^profiles/$',
        views.profileList,
        name='profiles_profile_list'),
    url(r'^profiles/(?P<username>\w+)/$',
        'profiles.views.profile_detail',
        sport_context,
        name='profiles_profile_detail'),
    url(r'^feeds/(?P<url>.*)/$',
        'django.contrib.syndication.views.feed',
        {'feed_dict': feeds}),
    url(r'^messages/$',
        direct_to_template,
        {'template': 'scheduler/messages.html'})
)

urlpatterns += patterns('',
    url(r'^attend/(?P<md_id>\d+)/$', views.attend, name='sch_matchday_attend'),
    url(r'^abandon/(?P<md_id>\d+)/$', views.abandon, name='sch_matchday_abandon'),    
    url(r'^addguest/(?P<md_id>\d+)/$', views.addGuest, name='sch_guest_add'),
    url(r'^delguest/(?P<md_id>\d+)/$', views.delGuest, name='sch_guest_del'),
    url(r'^links/delguest/$', views.delGuestCallback, name='sch_guest_ajax_del'),
    url(r'^addteam/(?P<md_id>\d+)/$', views.addTeam, name='sch_team_add'),
    url(r'^delteam/(?P<md_id>\d+)/$', views.delTeam, name='sch_team_del'),
    url(r'^links/delteam/$', views.delTeamCallback, name='sch_team_ajax_del'),
    url(r'^sendemail/(?P<md_id>\d+)/$', views.sendEmail, name='sch_email_send'),
    url(r'^comments/(?P<md_id>\d+)/$', views.comment, name='sch_comments'),
    url(r'^loadTeam/$', views.loadTeam, name='sch_team_ajax'),
    url(r'^addProposal/$', views.addProposal, name='sch_addproposal'),
    url(r'^proposal/(?P<pid>\d+)/delete/$', views.delProposal, name='sch_proposal_del'),
    url(r'^matchday/(?P<object_id>\d+)/teams/$', views.teamsManagement, name='sch_team_management'),
    url(r'deleteOrphanGps/$', views.deleteOrphanGuestPlayers, name='sch_orphangp_del'),
    url(r'uniqueGps/$', views.makeGuestPlayersUnique, name='sch_gp_unique'),
    url(r'mdbysport/(?P<sport>\w+)/$', views.matchday_by_sport, name='sch_matchday_by_sport'),
)

urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('scheduler.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^news/', include('news.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^forum/', include('forum.urls')),
)
# if we're in DEBUG mode, allow django to serve media
# This is considered inefficient and isn't secure.
from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

scheduler/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class Sport(models.Model):
    name = models.CharField(max_length=50, unique=True)
    active = models.BooleanField(default=True)
    icon = models.ImageField(upload_to="sport_icons", null=True)

    def __unicode__(self):
        return self.name

class PlayerProfile(models.Model):
    SPEED_CHOICES = ((u'SN', u'Snail'), (u'PD', u'Pedestrian'), (u'SP', u'Sprinter'), (u'RK', u'Rocket'),)
    STAMINA_CHOICES = ((u'SL', u'Sleep Walker'), (u'PR', u'Programmer'), (u'PD', u'Paladin LV7'), (u'MR', u'Marathonist'),)
    CONTROLL_CHOICES = ((u'LP', u'Light Post'), (u'EV', u'Evitationist'), (u'NW', u'Needle Worker'), (u'RN', u'Ronaldinho'),)
    SHOT_CHOICES = ((u'DP', u'Delicate'), (u'KK', u'Kicker'), (u'GD', u'Gigi Duru'), (u'GN', u'Gunner'),)
    user = models.ForeignKey(User, null=True, unique=True)
    alias_name = models.CharField(max_length=50, help_text='Name of a sport star of monumental proportions (e.g. Mutu).')
    email_subscription = models.ManyToManyField(Sport, null=True, blank=True, help_text='Sport email notification subscription')
    speed = models.CharField(null=True,blank=True, max_length=3, choices=SPEED_CHOICES)
    stamina = models.CharField(null=True,blank=True, max_length=3, choices=STAMINA_CHOICES)
    ball_controll = models.CharField(null=True,blank=True, max_length=3, choices=CONTROLL_CHOICES)
    shot_power = models.CharField(null=True,blank=True, max_length=3, choices=SHOT_CHOICES)

    @models.permalink
    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })

    def __unicode__(self):
        return self.user.username + "'s profile"

    def is_filled(self):
        return self.user.first_name != '' or self.user.last_name != '' or self.alias_name != ''

    def get_full_name(self):
        if self.is_filled():
            return self.user.first_name + ' ' + self.alias_name  + ' ' + self.user.last_name
        else:
            return self.user.username

class GuestPlayer(models.Model):
    friend_user = models.ForeignKey(User, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def __unicode__(self):
        return self.get_full_name() + ' invited by ' + self.friend_user.get_full_name()

    class Meta:
        unique_together = ('friend_user', 'first_name', 'last_name')

class MatchDay(models.Model):
    start_date = models.DateTimeField()
    location = models.CharField(max_length=50)
    sport_name = models.ForeignKey(Sport, related_name='%(class)s_sport', limit_choices_to = {'active': True})
    participants = models.ManyToManyField(User, null=True, blank=True)
    guest_stars = models.ManyToManyField(GuestPlayer, null=True, blank=True)

    def __unicode__(self):
        return self.sport_name.name\
        + ' ' + self.start_date.strftime('%d-%B-%Y')\
        + ' ' + self.location\
        + ' ' + self.start_date.strftime('%H:%M')

    def is_future(self):
        return datetime.today() < self.start_date
    is_future.short_description = 'Is in the future?'
    is_future.boolean = True

    class Meta:
        ordering = ["-start_date"]

    @models.permalink
    def get_absolute_url(self):
        return ('sch_matchday_detail', (), {'object_id': self.id })


class Team(models.Model):
    name = models.CharField(max_length=50)
    matchday = models.ForeignKey(MatchDay)
    participants = models.ManyToManyField(User, null=True, blank=True)
    guest_stars = models.ManyToManyField(GuestPlayer, null=True, blank=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('sch_team_management', (), { 'object_id': self.matchday.id })

    class Meta:
        unique_together = ('name', 'matchday')

def user_profile_handler(sender, **kwargs):
    newUser = kwargs['instance']
    if kwargs['created']:
        try:
            newUser.get_profile()
        except:
            pp = PlayerProfile(user = newUser)
            pp.save()

class Proposal(models.Model):
    user = models.ForeignKey(User)
    matchday = models.ForeignKey(MatchDay)
    teams = models.TextField()

    def __unicode__(self):
        return self.user.get_full_name() + "'s proposal for " + str(self.matchday)

    class Meta:
        unique_together = ('user', 'matchday')

post_save.connect(user_profile_handler, sender=User)

scheduler/forms.py
from django import forms
from registration.forms import RegistrationFormUniqueEmail
from registration.models import RegistrationProfile
from scheduler.models import GuestPlayer, Team, PlayerProfile, MatchDay, Sport
from registration.backends.default import DefaultBackend


attrs_dict = { 'class': 'required' }

class PlayerRegistrationBackend(DefaultBackend):
     def get_form_class(self, request):
         return PlayerRegistrationForm

     def register(self, request, **kwargs):
          new_user = super(PlayerRegistrationBackend, self).register(request, **kwargs)
          new_user.first_name = kwargs['first_name']
          new_user.last_name = kwargs['last_name']
          new_user.save()
          return new_user

class PlayerRegistrationForm(RegistrationFormUniqueEmail):
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

class PlayerProfileForm(forms.ModelForm):
    class Meta:
        model = PlayerProfile
        exclude = ('user',)

class GuestPlayerForm(forms.ModelForm):
    class Meta:
        model = GuestPlayer
        exclude = ('friend_user',)

class TeamForm(forms.ModelForm):
    class Meta:
        model = Team
        exclude = ('matchday', 'participants', 'guest_stars')

templates/scheduler/add_guest.html
<form method="post" action="{% url sch_guest_add md_id %}">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save Guest Details"/><input type="hidden" name="next" value="{% url sch_matchday_list %}" />
</form>

templates/scheduler/add_team.html
<form method="post" action="{% url sch_team_add md_id %}">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save Team"/><input type="hidden" name="next" value="{% url sch_team_ajax %}" />
</form>

templates/scheduler/comment.html
{% extends 'base.html' %}
{% load comments %}
{% load humanize %}
{% block title %}View Comments{% endblock %}
{% block content %}
{% get_comment_list for matchday as comment_list %}
{% for comment in comment_list %}
    <p class="comment"><span class="commentingUser">{{ comment.user_name }}:</span> {{ comment.comment }} <span class="dateTime">({{ comment.submit_date|date:"D d M Y"|naturalday }} {{ comment.submit_date|time:"H:i"}})</span></p>
{% endfor %}

{% if user.is_authenticated %}
    <h2>Leave a comment</h2>
    {% get_comment_form for matchday as form %}
    <form action="{% comment_form_target %}" method="POST">{% csrf_token %}
        {{ form.comment }}
        {{ form.content_type }}
        {{ form.object_pk }}
        {{ form.timestamp }}
        {{ form.security_hash }} <br>
        <input type="submit" value="Add comment" id="id_submit" />
        <input type="hidden" name="next" value="{% url sch_comments matchday.id %}" />
    </form>
{% else %}
    <h2><a href="{% url auth_login %}">Log in</a> to leave a comment</h2>
{% endif %}
{% endblock %}

templates/scheduler/del_guest.html
<table cellspacing="0" class="list">
    <thead>
    <tr>
        <th>Id#</th>
        <th>Guest name</th>
        <th>Action</th>
    </tr>
    </thead>
    {% for guest in guest_list %}
    <tbody>
    <tr>
        <td>{{ guest.id }}</td>
        <td>{{ guest.get_full_name }}</td>
        <td><a class="dellink" guestId="{{ guest.id }}" matchdayId="{{ md_id }}" href="#">Delete</a></td>
    </tr>
    </tbody>
    {% endfor %}
</table>

templates/scheduler/del_team.html
<table cellspacing="0" class="list">
    <thead>
    <tr>
        <th>Id#</th>
        <th>Team name</th>
        <th>Action</th>
    </tr>
    </thead>
    {% for team in team_list %}
    <tbody>
    <tr>
        <td>{{ team.id }}</td>
        <td>{{ team.name }}</td>
        <td><a class="dellink" teamId="{{ team.id }}" matchdayId="{{ md_id }}" href="#">Delete</a></td>
    </tr>
    </tbody>
    {% endfor %}
</table>

templates/scheduler/filtered_matchday_list.html
{% load humanize %}
{% load comments %}
<ul>
    {% for matchday in object_list %}
    {% get_comment_count for matchday as comment_count %}
    <li>
    {#{ matchday.id|ordinal }#}
	<img src="{{ matchday.sport_name.icon.url }}" height="16" width="16"/>
	<span class="sport">{{ matchday.sport_name }}</span>
        {{ matchday.start_date|date:"D d M Y"|naturalday }} -
        {{ matchday.location }} -
        {{ matchday.start_date|time:"H:i" }}
        <span md_id="{{ matchday.id }}">
        	{% if matchday.is_future %}
				{% if user in matchday.participants.all %}
					<a href="{% url sch_matchday_abandon matchday.id %}">Abandon</a>
				{% else %}
					<a href="{% url sch_matchday_attend matchday.id %}" href="#">Attend</a>
				{% endif %}
				<a onclick="showAddGuest('{% url sch_guest_add matchday.id %}')" href="#">G++</a>
				<a onclick="showDelGuest('{% url sch_guest_del matchday.id %}')" href="#">G--</a>
			{% endif %}
            <a class="md-detail-link" href="#">View</a>
            <a href="{% url sch_comments matchday.id %}">Comment ({{ comment_count }})</a>
        </span>
    </li>
    {% empty %}
        <li>Sorry, no matchdays for this sport!</li>
    {% endfor %}
</ul>
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
	{% if sport %}
            <a id="prev" href="/mdbysport/{{ sport }}/?page={{ page_obj.previous_page_number }}">previous</a>
	{% else %}
	    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
	{% endif %}
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
	{% if sport %}
            <a id="next" href="/mdbysport/{{ sport }}/?page={{ page_obj.next_page_number }}">next</a>
	{% else %}
	    <a href="?page={{ page_obj.next_page_number }}">next</a>
	{% endif %}
        {% endif %}
    </span>
</div>

templates/scheduler/index.html
{% extends "base.html" %}

{% block content %}
{% endblock %}

templates/scheduler/matchday_detail.html
{% load humanize %}
<h2>Matchday Information</h2>
<ul>
<li>Sport: {{ object.sport_name }}</li>
{% if not object.is_future %}
    <li>Date: Opened {{ object.start_date|timesince }} ago</li>
{% endif %}
<li>Location: {{ object.location }}</li>
<li>Date: {{ object.start_date|date:"D d M Y"|naturalday }} {{ object.start_date|time:"H:i" }}</li>

</ul>
Participants:
    <ol>
    {% for player in object.participants.all %}
        <li>{{ player.get_profile.get_full_name }}</li>
    {% empty %}
        <p>Sorry, no participants in this list!</p>
    {% endfor %}
    </ol>
Guest Stars:
    <ol>
        {% for guest in object.guest_stars.all %}
            <li>{{ guest.get_full_name }} invited by {{ guest.friend_user.get_profile.get_full_name }}</li>
        {% empty %}
            <p>Sorry, no guest stars in this list!</p>
        {% endfor %}
    </ol>
<div id="teams">
    {% for team in object.team_set.all %}
        <div id="team">
            <h4>Team {{ team.name }}</h4>
            <ul>
                {% for player in team.participants.all %}
                    <li>{{ player.get_full_name }}</li>
                {% endfor %}
                {% for player in team.guest_stars.all %}
                    <li>{{ player.get_full_name }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endfor %}
</div>
<div>
    <a href="{% url sch_team_management object.id %}">Teams Management</a>
    {% if user.is_staff and object.is_future %}
        <div type="hidden" id="email_form"></div>
        <a class="right" id="send_email" onclick="showEmailForm({{ object.id }})" href="#">Send invite email!</a>
    {% endif %}
</div>


templates/scheduler/matchday_list.html
{% extends "base.html" %}
{% load forum_tags %}
{% block title %}View MatchDays{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/matchdayFunctions.js"></script>
{% endblock %}
{% block content %}
<a  href="/"><img style="float:right;" src="{{ MEDIA_URL }}images/trophy.png"/></a>
<h2>Matchdays</h2>
<div id="matchdays" class="rounded-corners">
  <div id="md-filters">
    <a href="{% url sch_matchday_list %}">All</a>
    {% for sport_name in sport_list %}
		{% if sport_name.active %}
        	<a class="md-filter" id="{{ sport_name }}" href="{% url sch_matchday_by_sport sport_name %}">{{ sport_name }}</a>
		{% endif %}
    {% endfor %}
  </div>
  <div id="md-placeholder">
    {% include "scheduler/filtered_matchday_list.html" %}
  </div>
</div>
<div id="news-placeholder"></div>
<div id="latest-posts">
  <h2>Latest activity on the forum</h2>
<!--
{% forum_latest_posts 5 as latest_posts %}
<ul>
{% for post in latest_posts %}
<li><strong><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></strong> {{ post.latest_post_time|timesince }} ago</li>
{% endfor %}
</ul>
-->
{% forum_latest_thread_activity 5 as latest_activity %}
<ul>
{% for post in latest_activity %}
<p><strong><a href='{{ post.get_absolute_url }}'>{{ post.title }}</a></strong> {{ post.latest_post_time|timesince }} ago</p>
{% endfor %}
</ul>
</div>
{% endblock %}
{% block navbar%}
<a href="/profiles/">View all users</a>
{% endblock %}

templates/scheduler/messages.html
{% if messages %}
    <ul>
    {% for message in messages %}
        <li class="message" id="test_mes"> {{ message }} </li>
    {% endfor %}
    </ul>
{% endif %}

templates/scheduler/proposal_detail.html
<p><strong>{{ object.user.get_full_name }}</strong> proposed the folowing teams:</p>
<p><strong>{{ object.matchday }}</strong></p>
<p>{{ object.teams|safe }}</p>

templates/scheduler/send_email_form.html
{% load humanize %}
<form method="POST" action="{% url sch_email_send object.id %}">{% csrf_token %}
    <h4>Subject:</h4>
    <input type="text" name="subject" value="{{ object.sport_name }} invitation"/>
    <h4>Sport: {{ object.sport_name }}</h4>
    <h4>Body:</h4>
    <textarea rows="5" cols="30" name="message">
You are invited to come to the {{ object.sport_name }} matchday starting at
{{ object.start_date|time:"H:i" }} - {{ object.start_date|date:"D, d M Y"|naturalday }}
which will take place at {{ object.location }} arena.
Click 'Attend' at http://elMonumental.sro.oce.net/ to attend.
    </textarea>
    <input type="submit" value="Send Email!"/>
</form>

templates/scheduler/teams.html
{% extends "base.html" %}
{% load humanize %}
{% block title %}Create Teams{% endblock %}
{% block scripts %}
   <script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui.custom.min.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/teamFunctions.js"></script>
    <script type="text/javascript" src="{{ MEDIA_URL }}js/proposalFunctions.js"></script>
{% endblock %}
{% block content %}
<h2>Team Proposals</h2>
<ul>
{% for proposal in proposal_list %}
    <li>
        <a class="proposals_link" href="{% url sch_proposal_ajax proposal.id %}">{{ proposal }}</a>
        {% ifequal user proposal.user %}
            - <a class="delete_proposal_link" href="{% url sch_proposal_del proposal.id %}">Delete</a>
        {% endifequal %}
    </li>
{% empty %}
    <li>There are no proposals at this time.</li>

{% endfor %}
</ul>
{% if object.is_future %}
<h2>Matchday Information</h2>
<ul>
{% if not object.is_future %}
    <li>Date: Opened {{ object.start_date|timesince }} ago</li>
{% endif %}
<li>Location: {{ object.location }}</li>
<li>Date: {{ object.start_date|date:"D d M Y"|naturalday }} {{ object.start_date|time:"H:i" }}</li>
</ul>
{% if user.is_staff %}
<div>
    <a id="create_team_link" href="{% url sch_team_add object.id %}">Create Team</a>
    <a id="delete_team_link" href="{% url sch_team_del object.id %}">Delete Team</a>
</div>
{% endif %}
<div id="teams" md_id="{{ object.id }}">
    {% for team in object.team_set.all %}
        <div class="team rounded-corners" tm_id="{{ team.id }}">
            <h4 id="team_title">Team {{ team }} Players: <span class="count">0</span></h4>
            <ol class="sortable">
                <li class="drop-message">Drop players here!</li>
            </ol>
        </div>
    {% endfor %}
</div>
Participants:
    <ul>
    {% for player in object.participants.all %}
        <li class="draggable" pl_id="{{ player.id }}">{{ player.get_profile.get_full_name }}</li>
    {% endfor %}
    </ul>
Guest Stars:
    <ul>
        {% for guest in object.guest_stars.all %}
            <li class="draggable" gu_id="{{ guest.id }}">{{ guest.get_full_name }}</li>
        {% endfor %}
    </ul>
{% endif %}
{% endblock %}
{% block navbar%}
    <a href="{% url sch_team_management object.id %}">Reset</a>
    {% if object.is_future %}
        {% if user.is_staff %}
            <a id="save_teams_link" href="#">Save team</a>
        {% else %}
            <a id="save_proposal_link" href="#">Save proposal</a>
        {% endif %}
    {% endif %}
{% endblock %}