urls.py
from django.conf.urls.defaults import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    (r'^', include('scheduler.urls')),
    (r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('registration.backends.default.urls')),
    (r'^profiles/', include('profiles.urls')),
    (r'^news/', include('news.urls')),
    (r'^comments/', include('django.contrib.comments.urls')),
    (r'^forum/', include('forum.urls')),
)
# if we're in DEBUG mode, allow django to serve media
# This is considered inefficient and isn't secure.
from django.conf import settings
if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
    )

scheduler/models.py
from django.db import models
from datetime import datetime
from django.db.models.signals import post_save
from django.contrib.auth.models import User

class Sport(models.Model):
    name = models.CharField(max_length=50, unique=True)
    active = models.BooleanField(default=True)
    icon = models.ImageField(upload_to="sport_icons", null=True)

    def __unicode__(self):
        return self.name

class PlayerProfile(models.Model):
    SPEED_CHOICES = ((u'SN', u'Snail'), (u'PD', u'Pedestrian'), (u'SP', u'Sprinter'), (u'RK', u'Rocket'),)
    STAMINA_CHOICES = ((u'SL', u'Sleep Walker'), (u'PR', u'Programmer'), (u'PD', u'Paladin LV7'), (u'MR', u'Marathonist'),)
    CONTROLL_CHOICES = ((u'LP', u'Light Post'), (u'EV', u'Evitationist'), (u'NW', u'Needle Worker'), (u'RN', u'Ronaldinho'),)
    SHOT_CHOICES = ((u'DP', u'Delicate'), (u'KK', u'Kicker'), (u'GD', u'Gigi Duru'), (u'GN', u'Gunner'),)
    user = models.ForeignKey(User, null=True, unique=True)
    alias_name = models.CharField(max_length=50, help_text='Name of a sport star of monumental proportions (e.g. Mutu).')
    email_subscription = models.ManyToManyField(Sport, null=True, blank=True, help_text='Sport email notification subscription')
    speed = models.CharField(null=True,blank=True, max_length=3, choices=SPEED_CHOICES)
    stamina = models.CharField(null=True,blank=True, max_length=3, choices=STAMINA_CHOICES)
    ball_controll = models.CharField(null=True,blank=True, max_length=3, choices=CONTROLL_CHOICES)
    shot_power = models.CharField(null=True,blank=True, max_length=3, choices=SHOT_CHOICES)

    @models.permalink
    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })

    def __unicode__(self):
        return self.user.username + "'s profile"

    def is_filled(self):
        return self.user.first_name != '' or self.user.last_name != '' or self.alias_name != ''

    def get_full_name(self):
        if self.is_filled():
            return self.user.first_name + ' ' + self.alias_name  + ' ' + self.user.last_name
        else:
            return self.user.username

class GuestPlayer(models.Model):
    friend_user = models.ForeignKey(User, null=True)
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)

    def get_full_name(self):
        return self.first_name + ' ' + self.last_name

    def __unicode__(self):
        return self.get_full_name() + ' invited by ' + self.friend_user.get_full_name()

    class Meta:
        unique_together = ('friend_user', 'first_name', 'last_name')

class MatchDay(models.Model):
    start_date = models.DateTimeField()
    location = models.CharField(max_length=50)
    sport_name = models.ForeignKey(Sport, related_name='%(class)s_sport', limit_choices_to = {'active': True})
    participants = models.ManyToManyField(User, null=True, blank=True)
    guest_stars = models.ManyToManyField(GuestPlayer, null=True, blank=True)

    def __unicode__(self):
        return self.sport_name.name\
        + ' ' + self.start_date.strftime('%d-%B-%Y')\
        + ' ' + self.location\
        + ' ' + self.start_date.strftime('%H:%M')

    def is_future(self):
        return datetime.today() < self.start_date
    is_future.short_description = 'Is in the future?'
    is_future.boolean = True

    class Meta:
        ordering = ["-start_date"]

    @models.permalink
    def get_absolute_url(self):
        return ('sch_matchday_detail', (), {'object_id': self.id })


class Team(models.Model):
    name = models.CharField(max_length=50)
    matchday = models.ForeignKey(MatchDay)
    participants = models.ManyToManyField(User, null=True, blank=True)
    guest_stars = models.ManyToManyField(GuestPlayer, null=True, blank=True)

    def __unicode__(self):
        return self.name

    @models.permalink
    def get_absolute_url(self):
        return ('sch_team_management', (), { 'object_id': self.matchday.id })

    class Meta:
        unique_together = ('name', 'matchday')

def user_profile_handler(sender, **kwargs):
    newUser = kwargs['instance']
    if kwargs['created']:
        try:
            newUser.get_profile()
        except:
            pp = PlayerProfile(user = newUser)
            pp.save()

class Proposal(models.Model):
    user = models.ForeignKey(User)
    matchday = models.ForeignKey(MatchDay)
    teams = models.TextField()

    def __unicode__(self):
        return self.user.get_full_name() + "'s proposal for " + str(self.matchday)

    class Meta:
        unique_together = ('user', 'matchday')

post_save.connect(user_profile_handler, sender=User)

templates/profiles/create_profile.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save"/><input type="hidden" name="next" value="{% url profiles_profile_detail  user.username %}" />
</form>
{% endblock %}

templates/profiles/edit_profile.html
{% extends "base.html" %}
{% block content %}
<form method="post" action="">{% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Save"/><input type="hidden" name="next" value="{% url profiles_profile_detail user %}" />
</form>
{% endblock %}

templates/profiles/profile_detail.html
{% extends "base.html" %}

{% block content %}
<table cellspacing="0" class="list">
    <tr><td>First name:</td><td>{{ profile.user.first_name }}</td></tr>
    <tr><td>Last name:</td><td>{{ profile.user.last_name }}</td></tr>
    <tr><td>Email:</td><td>{{ profile.user.email }}</td></tr>
    <tr><td>Email subscriptions:</td><td>{% for subsc in profile.email_subscription.all %}{{ subsc.name }} {% endfor %}</td></tr>
    <tr><td>Alias name:</td><td>{{ profile.alias_name }}</td></tr>
    <tr><td>Speed:</td><td>{{ profile.get_speed_display }}</td></tr>
    <tr><td>Stamina:</td><td>{{ profile.get_stamina_display }}</td></tr>
    <tr><td>Ball controll:</td><td>{{ profile.get_ball_controll_display }}</td></tr>
    <tr><td>Shot power:</td><td>{{ profile.get_shot_power_display }}</td></tr>
</table>
<h2>Attendance Rates</h2>
{% load scheduler_tags %}

{% get_attendance %}
<ul>
    {% for sport, values in attendance_dict.items %}
        {% if sport.active %}
            <li><img src="{{ sport.icon.url }}" height="16" width="16"/>
                {{ sport }}: <span class="procentage">{{ values.1 }}</span>
            </li>
        {% endif %}
    {% endfor %}
</ul>
{% endblock %}
{% block navbar %}
  <a href="{% url profiles_edit_profile %}">Edit</a>
{% endblock %}

templates/profiles/profile_list.html
{% extends 'base.html' %}

{% block title %}View All Users{% endblock %}
{% block html_head %}
<link rel="stylesheet" href="{{ MEDIA_URL }}css/tablesorter.css" type="text/css" media="screen">
<link rel="stylesheet" href="{{ MEDIA_URL }}css/jquery.tablesorter.pager.css" type="text/css" media="screen">
<link type="text/css" href="{{ MEDIA_URL }}css/south-street/jquery-ui.custom.css" rel="stylesheet"/>
{% endblock %}
{% block scripts %}
<script type="text/javascript" src="{{ MEDIA_URL }}js/ui/i18n/jquery.ui.datepicker-ro.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery.tablesorter.pager.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/jquery-ui.custom.min.js"></script>
<script type="text/javascript" src="{{ MEDIA_URL }}js/dateFiltering.js"></script>
{% endblock %}

{% block content %}
<div class="right">
<form method="POST" action=".">{% csrf_token %}
    <label for="since">Attendance since:</label><input name="since" id="since" type="text"/>
    <input type="submit" value="Filter" />
    <!--a id="reset" href="#">Reset</a-->
</form>
<a href="{% url profiles_profile_list %}">Reset</a>
</div>
<h2>Users</h2>
<div  style="height: 600px; overflow: auto">
<table id="usersTable" class="list tablesorter" cellspacing="1" id="userlist">
<thead>
    <tr>
        <th>#</th>
        <th>FirstName</th>
        <th>AliasName</th>
        <th>LastName</th>
        <th>Speed</th>
        <th>Stamina</th>
        <th>BallControl</th>
        <th>ShotPower</th>
        {% for sport_name in sport_list %}
            {% if sport_name.active %}
             <th>{{ sport_name }}</th><th>%</th>
            {% endif %}
    	{% endfor %}
    </tr>
</thead>

<tbody>
{% include "profiles/profile_table.html"%}
</tbody>
</table>
<div id="pager"></div>
</div>
{% endblock %}

templates/profiles/profile_table.html
{% load scheduler_tags %}
    {% for profile in object_list %}
    {% get_attendance %}
    <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ profile.user.first_name }}</td>
        <td>{{ profile.alias_name }}</td>
        <td>{{ profile.user.last_name }}</td>
        <td>{{ profile.get_speed_display }}</td>
        <td>{{ profile.get_stamina_display }}</td>
        <td>{{ profile.get_ball_controll_display }}</td>
        <td>{{ profile.get_shot_power_display }}</td>
        {% for sport_name in sport_list %}
        {% if sport_name.active %}
        <td>{{ attendance_dict|attendance:sport_name }}</td><td><span class="procentage">{{ attendance_dict|procentage:sport_name }}</span></td>
        {% endif %}
        {% endfor %}
        <td>
            <a href="{% url profiles_profile_detail profile.user%}">View</a>
        </td>
    </tr>
    {% endfor %}